"""initial schema

Revision ID: eeabba7c3016
Revises: 
Create Date: 2026-02-20 17:23:41.754890
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eeabba7c3016'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('vad_model', sa.String(length=50), nullable=True),
    sa.Column('vad_threshold', sa.Float(), nullable=True),
    sa.Column('enable_vlm', sa.Boolean(), nullable=True),
    sa.Column('enable_agent', sa.Boolean(), nullable=True),
    sa.Column('agent_flow', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_table('camera_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'camera_id', name='uq_user_camera')
    )
    op.create_index(op.f('ix_camera_access_camera_id'), 'camera_access', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_access_id'), 'camera_access', ['id'], unique=False)
    op.create_index(op.f('ix_camera_access_user_id'), 'camera_access', ['user_id'], unique=False)
    op.create_table('daily_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('avg_vad_time', sa.Float(), nullable=True),
    sa.Column('avg_vlm_time', sa.Float(), nullable=True),
    sa.Column('avg_agent_time', sa.Float(), nullable=True),
    sa.Column('max_vad_score', sa.Float(), nullable=True),
    sa.Column('min_vad_score', sa.Float(), nullable=True),
    sa.Column('vlm_type_counts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'date', name='uq_camera_date')
    )
    op.create_index(op.f('ix_daily_statistics_camera_id'), 'daily_statistics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_daily_statistics_date'), 'daily_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_statistics_id'), 'daily_statistics', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('vad_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('vlm_type', sa.String(length=100), nullable=True),
    sa.Column('vlm_description', sa.Text(), nullable=True),
    sa.Column('vlm_confidence', sa.Float(), nullable=True),
    sa.Column('agent_actions', sa.JSON(), nullable=True),
    sa.Column('agent_response_time', sa.Float(), nullable=True),
    sa.Column('clip_path', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_acknowledged'), 'events', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_vlm_type'), 'events', ['vlm_type'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vlm_type', sa.String(length=100), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_camera_id'), 'notification_rules', ['camera_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_id'), 'notification_rules', ['id'], unique=False)
    op.create_index(op.f('ix_notification_rules_user_id'), 'notification_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_vlm_type'), 'notification_rules', ['vlm_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_rules_vlm_type'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_user_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_camera_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_events_vlm_type'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_index(op.f('ix_events_acknowledged'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_daily_statistics_id'), table_name='daily_statistics')
    op.drop_index(op.f('ix_daily_statistics_date'), table_name='daily_statistics')
    op.drop_index(op.f('ix_daily_statistics_camera_id'), table_name='daily_statistics')
    op.drop_table('daily_statistics')
    op.drop_index(op.f('ix_camera_access_user_id'), table_name='camera_access')
    op.drop_index(op.f('ix_camera_access_id'), table_name='camera_access')
    op.drop_index(op.f('ix_camera_access_camera_id'), table_name='camera_access')
    op.drop_table('camera_access')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
